<a href="https://colab.research.google.com/github/detok3585/Python_Analytics/blob/main/lee_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


1.
0부터 10까지의 난수를 이용하여 3*3 생성



In [16]:
import numpy as np

#np.randomseed(19940119)
x = np.random.randint(0,11,(3,3))
x

array([[1, 4, 2],
       [5, 9, 6],
       [0, 0, 9]])


2.
평균이 0 이고, 표준편차가 1인 3*3 난수 정규분포를 생성


In [19]:
y = np.random.normal(0,1,size=(3, 3))
y

array([[-2.16598918, -0.38625748, -1.79595784],
       [-0.63922692, -0.12036261, -0.83994303],
       [-1.31567906,  0.64240695, -0.97268623]])


3.
1부터 12까지의 수로 이루어진 1차원(1*12) -> 2차원(3*4)로 변경


In [23]:
z = np.arange(1,13)
zz = z.reshape(3,4)
zz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

4.
arr = [[1, 2, 3],
       [4, 5, 6]]
을 사용하여       
[[1, 2, 3, 1, 2, 3],
 [4, 5, 6, 4, 5, 6]]
형태로 만들어라


In [29]:
arr = [[1, 2, 3], [4, 5, 6]] 
arrr = [[arr[0]+arr[0]],[arr[1]+arr[1]]]
arrr

[[[1, 2, 3, 1, 2, 3]], [[4, 5, 6, 4, 5, 6]]]

arr2 =
[[1, 2, 3],
 [2, 2, 2],
 [3, 2, 1]]


6. arr2 각 행을 더한 1차원 배열 생성
7. arr2 각 열별 [최대값, 최솟값] 배열 생성

In [40]:
arr2 = [[1, 2, 3], [2, 2, 2], [3, 2, 1]]
arrr2 = np.array(arr2[0]) + np.array(arr2[1]) + np.array(arr2[2])
print(arrr2)
arrrr2 = np.sum(arr2, axis = 1)
print(arrrr2)

[6 6 6]
[6 6 6]



8. 0 부터 1까지를 5개로 나누어 출력하라. (ex) [0, 0.25, 0.5, 0.75, 1] )


In [43]:
arr3 = np.linspace(0, 1, 5)
arr3

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

df1 = pd.DataFrame([[1, 2, 3], [4, 5, 6], [np.nan, 7, 8], [10, np.nan, 12]])

9. df1에서 NaN값이 있는 행을 제거하여 출력
10. df1에서 NaN값을 평균으로 대체하여 출력


In [56]:
import pandas as pd
from pandas import DataFrame as df

df1 = pd.DataFrame([[1, 2, 3], [4, 5, 6], [np.nan, 7, 8], [10, np.nan, 12]])
drop_df1 = df1.dropna(axis =0)
print(drop_df1)
drop_df11 = df1.fillna(df1.mean())
print(drop_df11)

     0    1  2
0  1.0  2.0  3
1  4.0  5.0  6
      0         1   2
0   1.0  2.000000   3
1   4.0  5.000000   6
2   5.0  7.000000   8
3  10.0  4.666667  12




df2 = pd.DataFrame({'name': ['이순신', '강감찬', '을지문덕', '김유신'], 'dept': ['연구개발', '영업', '연구개발', '인사']})
                    
df3 = pd.DataFrame({'emp_name': ['이순신', '강감찬', '을지문덕', '김유신'], 'project': ['S', 'D', 'A', 'S']})


11. df2와 df3 을 df2의 name과 df3의 emp_name을 사용하여 inner Join
12. df2와 df3 을 df2의 name과 df3의 emp_name을 사용하여 outer Join 



In [57]:
df2 = pd.DataFrame({'name': ['이순신', '강감찬', '을지문덕', '김유신'], 'dept': ['연구개발', '영업', '연구개발', '인사']})      
df3 = pd.DataFrame({'emp_name': ['이순신', '강감찬', '을지문', '김유신'], 'project': ['S', 'D', 'A', 'S']})

df_inner = pd.merge(df2, df3 , left_on = 'name', right_on = 'emp_name', how = 'inner')
print(df_inner)

df_outer = pd.merge(df2, df3 , left_on = 'name', right_on = 'emp_name', how = 'outer')
print(df_outer)

  name  dept emp_name project
0  이순신  연구개발      이순신       S
1  강감찬    영업      강감찬       D
2  김유신    인사      김유신       S
   name  dept emp_name project
0   이순신  연구개발      이순신       S
1   강감찬    영업      강감찬       D
2  을지문덕  연구개발      NaN     NaN
3   김유신    인사      김유신       S
4   NaN   NaN      을지문       A


\
seaborn 타이타닉 데이터 셋을 사용
import seaborn as sb
titanic = sb.load_dataset("titanic")


13. 성별을 그룹화하여, 각 성별 생존여부 평균을 구하라.
14. 성별(행)과 클래스(열)로 그룹화하여, 생존여부 평균을 구하라.

In [59]:
import seaborn as sb
titanic = sb.load_dataset("titanic")
titanic

survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0           0       3    male  22.0  ...   NaN  Southampton     no  False
1           1       1  female  38.0  ...     C    Cherbourg    yes  False
2           1       3  female  26.0  ...   NaN  Southampton    yes   True
3           1       1  female  35.0  ...     C  Southampton    yes  False
4           0       3    male  35.0  ...   NaN  Southampton     no   True
..        ...     ...     ...   ...  ...   ...          ...    ...    ...
886         0       2    male  27.0  ...   NaN  Southampton     no   True
887         1       1  female  19.0  ...     B  Southampton    yes   True
888         0       3  female   NaN  ...   NaN  Southampton     no  False
889         1       1    male  26.0  ...     C    Cherbourg    yes   True
890         0       3    male  32.0  ...   NaN   Queenstown     no   True

[891 rows x 15 columns]

In [66]:
titanic_sex = titanic.groupby(['sex'])
print(titanic_sex['survived'].mean())

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64


In [67]:
titanic_sexclass = titanic.groupby(['sex','class'])
print(titanic_sexclass['survived'].mean())

sex     class 
female  First     0.968085
        Second    0.921053
        Third     0.500000
male    First     0.368852
        Second    0.157407
        Third     0.135447
Name: survived, dtype: float64
